(cl:defpackage tracer_msgs-msg
  (:use )
  (:export
   "<TRACERBMSSTATUS>"
   "TRACERBMSSTATUS"
   "<TRACERLIGHTCMD>"
   "TRACERLIGHTCMD"
   "<TRACERLIGHTSTATE>"
   "TRACERLIGHTSTATE"
   "<TRACERMOTORSTATE>"
   "TRACERMOTORSTATE"
   "<TRACERRSSTATUS>"
   "TRACERRSSTATUS"
   "<TRACERSTATUS>"
   "TRACERSTATUS"
   "<UARTTRACERMOTORSTATE>"
   "UARTTRACERMOTORSTATE"
   "<UARTTRACERSTATUS>"
   "UARTTRACERSTATUS"
  ))

